# Generated by Django 4.2.2 on 2023-06-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='img_url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
